parse:
  additional_commands:
    omnitrace_checkout_git_submodule:
      flags:
      - RECURSIVE
      kwargs:
        RELATIVE_PATH: '*'
        WORKING_DIRECTORY: '*'
        TEST_FILE: '*'
        REPO_URL: '*'
        REPO_BRANCH: '*'
        ADDITIONAL_COMMANDS: '*'
    omnitrace_save_variables:
      kwargs:
        VARIABLES: '*'
        CONDITION: '*'
    omnitrace_restore_variables:
      kwargs:
        VARIABLES: '*'
        CONDITION: '*'
    omnitrace_add_test:
      flags:
        - SKIP_BASELINE
        - SKIP_REWRITE
        - SKIP_RUNTIME
        - SKIP_SAMPLING
      kwargs:
        NAME: '*'
        TARGET: '*'
        MPI: '*'
        NUM_PROCS: '*'
        REWRITE_TIMEOUT: '*'
        RUNTIME_TIMEOUT: '*'
        REWRITE_ARGS: '*'
        RUNTIME_ARGS: '*'
        RUN_ARGS: '*'
        ENVIRONMENT: '*'
        LABELS: '*'
        PROPERTIES: '*'
        RUNTIME_PASS_REGEX: '*'
        RUNTIME_FAIL_REGEX: '*'
        REWRITE_PASS_REGEX: '*'
        REWRITE_FAIL_REGEX: '*'
        REWRITE_RUN_PASS_REGEX: '*'
        REWRITE_RUN_FAIL_REGEX: '*'
    omnitrace_target_compile_definitions:
      kwargs:
        PUBLIC: '*'
        PRIVATE: '*'
        INTERFACE: '*'
    omnitrace_add_bin_test:
      flags:
      - WILL_FAIL
      kwargs:
        NAME: '*'
        ARGS: '*'
        LABELS: '*'
        TARGET: '*'
        DEPENDS: '*'
        COMMAND: '*'
        TIMEOUT: '*'
        PROPERTIES: '*'
        ENVIRONMENT: '*'
        WORKING_DIRECTORY: '*'
        PASS_REGEX: '*'
        FAIL_REGEX: '*'
        SKIP_REGEX: '*'
    omnitrace_add_python_test:
      flags:
      - STANDALONE
      kwargs:
        NAME: '*'
        FILE: '*'
        TIMEOUT: '*'
        PROFILE_ARGS: '*'
        RUN_ARGS: '*'
        ENVIRONMENT: '*'
        LABELS: '*'
        DEPENDS: '*'
        COMMAND: '*'
        PROPERTIES: '*'
        PYTHON_EXECUTABLE: '*'
        PYTHON_VERSION: '*'
        PASS_REGEX: '*'
        FAIL_REGEX: '*'
        SKIP_REGEX: '*'
    rocm_version_message:
      flags:
        - STATUS
        - WARNING
        - SEND_ERROR
        - FATAL_ERROR
        - AUTHOR_WARNING
    omnitrace_find_python:
      flags:
        - REQUIRED
        - QUIET
      kwargs:
        VERSION: '*'
        ROOT_DIR: '*'
        COMPONENTS: '*'
    omnitrace_python_console_script:
      kwargs:
        VERSION: '*'
        ROOT_DIR: '*'
    omnitrace_pybind11_add_module:
      flags:
        - MODULE
        - SHARED
        - EXCLUDE_FROM_ALL
        - NO_EXTRAS
        - SYSTEM
        - THIN_LTO
        - LTO
      kwargs:
        PYTHON_VERSION: '*'
        CXX_STANDARD: '*'
        VISIBILITY: '*'
    omnitrace_directory:
      flags:
        - MKDIR
        - FAIL
      kwargs:
        PREFIX: '*'
        OUTPUT_VARIABLE: '*'
        WORKING_DIRECTORY: '*'
        PATHS: '*'
    omnitrace_check_python_dirs_and_versions:
      flags:
        - UNSET
        - FAIL
      kwargs:
        RESULT_VARIABLE: '*'
        OUTPUT_VARIABLE: '*'
  override_spec: {}
  vartags: []
  proptags: []
format:
  disable: false
  line_width: 90
  tab_size: 4
  use_tabchars: false
  fractional_tab_policy: use-space
  max_subgroups_hwrap: 2
  max_pargs_hwrap: 8
  max_rows_cmdline: 2
  separate_ctrl_name_with_space: false
  separate_fn_name_with_space: false
  dangle_parens: false
  dangle_align: child
  min_prefix_chars: 4
  max_prefix_chars: 10
  max_lines_hwrap: 2
  line_ending: unix
  command_case: lower
  keyword_case: upper
  always_wrap: []
  enable_sort: true
  autosort: false
  require_valid_layout: false
  layout_passes: {}
markup:
  bullet_char: '*'
  enum_char: .
  first_comment_is_literal: false
  literal_comment_pattern: null
  fence_pattern: ^\s*([`~]{3}[`~]*)(.*)$
  ruler_pattern: ^\s*[^\w\s]{3}.*[^\w\s]{3}$
  explicit_trailing_pattern: '#<'
  hashruler_min_length: 10
  canonicalize_hashrulers: true
  enable_markup: true
lint:
  disabled_codes: []
  function_pattern: '[0-9a-z_]+'
  macro_pattern: '[0-9A-Z_]+'
  global_var_pattern: '[A-Z][0-9A-Z_]+'
  internal_var_pattern: _[A-Z][0-9A-Z_]+
  local_var_pattern: '[a-z][a-z0-9_]+'
  private_var_pattern: _[0-9a-z_]+
  public_var_pattern: '[A-Z][0-9A-Z_]+'
  argument_var_pattern: '[a-z][a-z0-9_]+'
  keyword_pattern: '[A-Z][0-9A-Z_]+'
  max_conditionals_custom_parser: 2
  min_statement_spacing: 1
  max_statement_spacing: 2
  max_returns: 6
  max_branches: 12
  max_arguments: 5
  max_localvars: 15
  max_statements: 50
encode:
  emit_byteorder_mark: false
  input_encoding: utf-8
  output_encoding: utf-8
misc:
  per_command: {}
